### ISSUE TITLE
name 'pred_train' is not defined

### ISSUE THREAD

**Issue by larrycai** [TreeinRandomForest/kubeflow_usecases#2]
all others work fine, it raise error when coming to appendix, do we expect to work?

````
(pred_train > 0.5).int()
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
Input In [37], in <module>
----> 1 (pred_train > 0.5).int()

NameError: name 'pred_train' is not defined
````

will be nice to fix this error as well

**Comment by larrycai** [comment]
noticed, just move one line (in later cell here)

````
pred_train = net(features_tensor).squeeze()
````

**Comment by nakfour** [comment]
Hi @larrycai which chapter and section is this error in?

**Comment by larrycai** [comment]
Ch2/Chapter 2 Supervised Learning on a Synthetic Dataset.ipynb

**Comment by nakfour** [comment]
Thanks for the catch @larrycai , its fixed
